# Start with a base image containing Java runtime
FROM openjdk:25-ea-21-jdk-slim

# Information around who maintain the image
LABEL maintainer="Eazybytes"

# Add the application's jar to the image
COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

# Execute the application
ENTRYPOINT ["java","-jar","/accounts-0.0.1-SNAPSHOT.jar"]